### ISSUE TITLE
get_userhome() and get_user() rely on unix-based OS

### ISSUE THREAD

**Issue by crew102** [vsoch/watchme#19]
`get_userhome()` relies on the `pwd` package, which assumes we're on a unix-based OS (see https://docs.python.org/2/library/pwd.html#module-pwd). Since `get_user()` was calling  `get_userhome()`, any use of either of these functions on a Windows system would likely cause trouble.  I'll submit a PR in a second that'll provide a platform-independent solution to getting username and home dir.

**Comment by vsoch** [comment]
I'm so glad you caught this! I definitely don't test with Windows in mind (and I'll keep this in mind for future things).

**Comment by crew102** [comment]
Hmmm, yeah, so the test you have is still got gonna pass on Windows. More importantly, you can't assume that a user will have a home dir (on any platform) that will start with, for example, `/Users` or `/home`, as you have done in the test. It's just a convention for users to have their home dirs in these locations, and users can change the folder location if they want to (though I'm sure it's not typical). 

Also, it's probably a good idea to address any issues you have with a contributor's PR (i.e., #20) in the PR itself, as opposed to opening a separate PR with a combination of two separate issues (i.e., PR #22 that seems to address issue #20 and some misc item that was discussed in #21).

**Comment by vsoch** [comment]
Thanks for the suggestion. I’m an experienced GitHub user and it was easier for me to do the fix myself.

Why will the test not pass on Windows?  I test for the platform and essentially do nothing if it’s windows. 

 The tests are somewhat artificially set up to run in the continuous integration  for the most part .  It’s typically only Linux sys admin’s that actually run the tests.  You’ll also notice in the set up that the software is not intended for windows so it’s not my direct priority to jump through hoops to support it.

**Comment by crew102** [comment]
Oh, I see you don't have an assertion for Windows. Like I said, you still can't assume that homedirs will be in a certain folder. 

> You’ll also notice in the set up that the software is not intended for windows so it’s not my direct priority to jump through hoops to support it.

Didn't notice this. So does your package not build on Windows? If so, that's a bigger issue.

**Comment by vsoch** [comment]
I don't typically develop or test for Windows. I don't see any reason why it wouldn't build, but it's not something I support. I maintain a lot of OS software, typically for science (unix/linux based) and this means not jumping through hoops for Windows. You are free to disagree.
