### ISSUE TITLE
Missing required dependency?

### ISSUE THREAD

**Issue by andreysmelter** [vsoch/watchme#23]
Dear @vsoch

Below is the example from Getting Started Documentation - initializing default urls type watcher and adding monitoring GitHub url task.

## Expected Behavior

Running this in a clean virtual environment with only `watchme` and its dependencies installed

`watchme add watcher task-singularity-release url@https://github.com/sylabs/singularity/releases`
`$ watchme run watcher`
Process the `task-singularity-release`

## Actual Behavior

Import error due to missing `requests` library dependency.

```
...
  File "/python3.5/site-packages/watchme/watchers/urls/__init__.py", line 50, in export_func
    from .tasks import get_task as func
  File "/python3.5/site-packages/watchme/watchers/urls/tasks.py", line 13, in <module>
    from .helpers import (
  File "/python3.5/site-packages/watchme/watchers/urls/helpers.py", line 13, in <module>
    import requests
ImportError: No module named 'requests'
```

## Steps to Reproduce

`$ watchme run watcher`

## Context

* Operating System: Fedora Linux
* watchme version: 0.0.14
* python version: Python 3.5

## Possible Fix

Add `requests` as a required dependency under `version.py` file since the `type = urls` watcher is a default watcher, e.g.:

```
INSTALL_REQUIRES = (
    ('python-crontab', {"min_version": "2.3.6"}),
    ('configparser', {"min_version": "3.5.3"}),
    ('requests', {"min_version": "2.21.0"})
)
```

**Comment by vsoch** [comment]
Will fix this right away!

**Comment by vsoch** [comment]
Here you go @andreysmelter https://github.com/vsoch/watchme/pull/24
I can wait for more review to update the PR if there are any other issues, we can release 0.0.15 with all the changes requested. (ha, requested :) )

**Comment by andreysmelter** [comment]
Thanks!

I think `requirements.txt` file also needs to be updated as it only has `python-crontab` in it.

**Comment by vsoch** [comment]
All set, completely forgot about that guy.
