### ISSUE TITLE
Docs: watchme init

### ISSUE THREAD

**Issue by andreysmelter** [vsoch/watchme#27]
## Expected Behavior

```
watchme init --help
usage: watchme init [-h] [--empty] [--watcher WATCHER] [--base BASE]

optional arguments:
  -h, --help         show this help message and exit
  --empty            don't create the default watcher folder
  --watcher WATCHER  the watcher to create (defaults to watcher)
  --base BASE        the watcher base (defaults to $HOME/.watchme)
```

## Actual Behavior

```
usage: watchme init [-h] [--empty]

optional arguments:
  -h, --help  show this help message and exit
  --empty     don't create the default watcher folder
```

So running...

```
watchme init --watcher TESTWATCHER
watcher already exists: /home/username/.watchme/watcher
```
...will not initialize a new `TESTWATCHER`.

## Possible Fix

This functionality probably moved to `watcher create` command and Getting Started Guide needs to be updated?

**Comment by vsoch** [comment]
The get started guide must have a typo - the init command isn't intended to create a watcher (the help you found is correct). It simply creates an (empty) watcher base. So when you do:

```bash
$ watchme init <args>
```
It's only going to see that the base exists. Likely the typo in the docs just needs to be watchme create - taking a look now!

**Comment by vsoch** [comment]
Thanks for catching this - I've updated the getting started pages so it's more clear:

https://github.com/vsoch/watchme/pull/24/commits/fb967db2ed32c7ca46e2c1faeae884233bb6e860

When I get through the rest of the review and you are happy with the edits, we can merge that PR (and give one final look over).
