### ISSUE TITLE
Paper: figure captions

### ISSUE THREAD

**Issue by andreysmelter** [vsoch/watchme#28]
## Figure captions need to be updated?

For example,

Figure 1: img/virtual-memory-used.png
to 
Figure 1: Virtual memory usage graph?

**Comment by vsoch** [comment]
Do you know how to do this?

**Comment by vsoch** [comment]
oh derp, just kidding, I know how to do this :)

**Comment by vsoch** [comment]
https://github.com/vsoch/watchme/pull/24/commits/0add420384706ea1b5969ecc651c76ee9ced6b3c
