### ISSUE TITLE
Values are not committed

### ISSUE THREAD

**Issue by sfischer13** [vsoch/watchme#48]
For some reason, the values of my watchers are not committed. If I run my watchers, all tasks produce results, but I cannot export values as there are no commits yet. `git` is installed and there is a repository in the watcher's directory.

Do you have any ideas how I could locate the error?

**Comment by vsoch** [comment]
Can you give me something to reproduce? You should minimally see that the watchme.cfg is added and committed. For tasks, if there aren't any changes from a previous time, you wouldn't see commits (no change == no commit). If you want to test the tasks, you can do any of the following:

```
watchme run <watcher> <task> --test
watchme run <watcher> <task> --test --serial
```

**Comment by vsoch** [comment]
you can use `git log` to show what has been committed.

**Comment by vsoch** [comment]
Any updates @sfischer13 ? Did you try git log / have any updates we can discuss to figure out the issue?

**Comment by vsoch** [comment]
@sfischer13 I haven't heard from you in over a month, so I'm closing the issue.
