### ISSUE TITLE
Error running task, with no further information

### ISSUE THREAD

**Issue by rknobbe** [vsoch/watchme#69]
## Expected Behavior

results similar to Getting Started guide

## Actual Behavior
`[1/1] |===================================| 100.0%
ERROR Error running task.`

## Steps to Reproduce

Followed all the steps in Getting Started, ended up with watchme.cfg that looks like this:
`
[task-singularity-release]
url = https://github.com/sylabs/singularity/releases
active = true
type = urls
`
ran this
`$ watchme run watcher task-singularity-release`

got this
`Found 1 contender tasks.
[1/1] |===================================| 100.0%
ERROR Error running task.`

## Context

[provide more detailed introduction to the issue itself . This is for make a reproducible issue.]
* Operating System: "Ubuntu 20.04.2 LTS"
 Linux zbox 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* watchme version: 0.0.28
* python version: 3.8.5

## Failure Logs

if only there were failure logs captured I would post them

## Possible Fix

[ the suggest fixes or reasons for the bug]

**Comment by vsoch** [comment]
Did you try the correct url? https://github.com/hpcng/singularity/releases. The repository has changed since writing this tool.

**Comment by rknobbe** [comment]
Same error regardless of the URL.  And yes, I did try it just now with https://github.com/hpcng/singularity/releases

**Comment by vsoch** [comment]
Please see the section on debugging - https://vsoch.github.io/watchme/getting-started/debugging/ - you should add the `--test` and `--serial` flags to see why it's failing.

**Comment by rknobbe** [comment]
Thanks! The problem indicated in the debugging page (save_as = text) is exactly the problem I was having with the Getting Started example. Perhaps you should correct the Getting Started guide to add that parameter?

**Comment by vsoch** [comment]
Absolutely! Could you point me to the link where you found the mistake?

**Comment by vsoch** [comment]
Found it! Will have a PR in soon.

**Comment by vsoch** [comment]
Thanks for opening the issue! The docs have been updated. https://vsoch.github.io/watchme/getting-started/index.html
